### PR TITLE
feat: add events for interaction with/by the TrashCans Module

### PR DESCRIPTION
**Pull request by FourtySeven047**
## Description

This pull request adds multiple events and a enum to create the possibilty for an interaction with the trash can logic. Those changes are necessary for future systems.

## Important Changes

- **UserInteractTrashCanEvent:** This event is the main event and inherited in every other trashcans event. Every entry seen in the "TrashCanInteraction" enum is beeing called here. 

The other events are self-explanatory.

## Additional Information

- I have performed a self-review of my own code
- I have commented my code

### CODE REVIEW

**Comment by Snabeldier** [comment]
well documented!

The use of an enum to represent different kinds of trashcans is redudant and should be omitted. You already use different events for each kind of interaction, so there is no need to habe an extra enum. 

There's also some java doc missing. Especially when working with events, it's super mandatory to know exactly when that event get's called. Please add some further explanations about that, since the event's name isn't that explanatory.

Your events also have no option to be manipulated or cancelled. At the moment, other modules are only permitted to get notified that someone interacted with a trashcan but they are neither allowed to cancel that nor to change the items given by the trashcan. Consider to add that :)

Still a great PR, please ask for help if you need it :)

**Comment by FourtySeven047** [comment]
Thank you for the feedback.

I have now added all the requested additions. Could you please take a look at them and share your review?

**Comment by Snabeldier** [comment]
Way better!

Please use lombok when possible! There are many Setters and Getters which could be replaced :)
Also consider to add the trashcan-block to the events so other modules are able to make decisions based on the trashcan location

The FractionalClearTrashCanEvent is nice, but not well named. Since the players that interact with trashcans in the context of a fraction job are always clearing the trashcan (They don't search through them), we can rename that event to TrashCanClearEvent

Please make UserInteractTrashCanEvent abstract.

Consider adding a TrashcanManager class to allow other modules to gather information about trashcans in total. There may be some methods like boolean isTrashCan(Block), Block getNearestTrashCan(Location), int getTotalTrashcans(), boolean isFull(Block).
You can copy the structure of these managers from other managers in Core :)

Thank you for your work!

**Comment by Snabeldier** [comment]
Nice!
Please add lombok @Setter and @Getter to UserInteractTrashCanEvent

**Comment by FourtySeven047** [comment]
Sure!

**Comment by Snabeldier** [comment]
Some small tweaks:

`    /**
     * Returns whether the trash can is full. If the block is not a trash can a {@code NullPointerException} will be thrown.
     *
     * @param block the block of the trash can
     * @return {@code true} if the trash can is full, {@code false} otherwise
     */
    public static boolean isFull(Block block) {
        return manager.isFull(block);
    }`

Throwing a NullPointerException if the block isn't a trash can is weird... 
Either consider adding a TrashCan-class to avoid these kind of issues, or throw an exception like InvalidArgumentException (you could also create your own exception, but that might be an overkill here)

Same with isEmpty()

With addItem(), removeItem() and clear() you don't throw a NPE :D 

`
    /**
     * Returns the peak ItemStack of the trash can. If the trash can is empty a {@code NullPointerException} will be thrown.
     *
     * @param block the block of the trash can
     * @return the peak ItemStack
     */
    public static ItemStack getPeak(Block block) {
        return manager.getPeak(block);
    }
`

Here is something more severe: You also throw a NullPointerException if the trash can is empty. What's the issue with returning null? There is no need to throw an exception here. If a module doesn't handle a null-return, it will just throw a NullPointerException there :D

**Comment by FourtySeven047** [comment]
Thank you for your review :>

To maintain consistency throughout the code I decided to throw  Exceptions if the block is not a trash can instead of returning null values. I have customized the JavaDoc following that principle.

I will set the idea for a TrashCan-class aside because I cant think of a use case that the Manager could not comply with soon.

**Comment by Snabeldier** [comment]
Great work!
Consider to add a FakeBlock class in the future to bundle all the methods that may throw an exception if there is no trashcan at the given block. This would make it easier to use this part of the api :)

**Pull request merged**
